---
################################################################################
# VOLUMES
################################################################################
volumes:
  db: {}

################################################################################
# SERVICES
################################################################################
services:
  # ------------------------------------------------------------
  # PHP
  # ------------------------------------------------------------
  php:
    image: devilbox/php-fpm:${PHP_VERSION:-8.2}-work
    working_dir: /var/www/default

    volumes:
      - .:/var/www/default:rw

    extra_hosts:
      - host.docker.internal:host-gateway

    environment:
      TEST_DATABASE_HOST: db
      TEST_DATABASE_PORT: 3306
      TEST_DATABASE_NAME: integration_test
      TEST_DATABASE_USER: root
      TEST_DATABASE_PASSWORD: ''

  # ------------------------------------------------------------
  # Web Server (Apache)
  # ------------------------------------------------------------
  httpd:
    image: devilbox/apache-${APACHE_VERSION:-2.4}:alpine
    ports:
      - ${HTTPD_PORT:-0}:80

    volumes:
      - .:/var/www/default:ro

    environment:
      MAIN_VHOST_DOCROOT_DIR: site
      MAIN_VHOST_BACKEND: conf:phpfpm:tcp:php:9000

  # ------------------------------------------------------------
  # Database
  # ------------------------------------------------------------
  db:
    image: mariadb:${MARIADB_VERSION:-lts}
    ports:
      - ${DB_PORT:-0}:3306

    volumes:
      - db:/var/lib/mysql:rw

    environment:
      MARIADB_ROOT_PASSWORD: ''
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: ${MARIADB_ALLOW_EMPTY_ROOT_PASSWORD:-yes}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-espocrm}
